import { ItemData } from "../typings/item";

// dev-only mock — mirrors what the server would normally send via the
// 'init' NUI event. Covers one item per rarity tier, six weapons with
// different component loadouts, and a container, so every card/tooltip/modal
// variant can be exercised from `bun run dev` without a real server.
export const Items: {
  [key: string]: ItemData | undefined;
} = {
  // ---------- one item per rarity ----------
  water: {
    name: "water",
    close: false,
    label: "Water",
    stack: true,
    usable: true,
    count: 0,
    description: "Restores thirst. Drink immediately.",
    rarity: "comum",
  },
  bandage: {
    name: "bandage",
    close: false,
    label: "Bandage",
    stack: true,
    usable: true,
    count: 0,
    description: "Stops bleeding and restores a little health.",
    rarity: "incomum",
  },
  radio: {
    name: "radio",
    close: false,
    label: "Radio",
    stack: false,
    usable: true,
    count: 0,
    description: "Allows communication over a set frequency with your group.",
    rarity: "raro",
    grid: { width: 1, height: 2 },
  },
  parachute: {
    name: "parachute",
    close: false,
    label: "Parachute",
    stack: false,
    usable: true,
    count: 0,
    description: "Deploys automatically when falling from a great height.",
    rarity: "epico",
    grid: { width: 2, height: 3 },
  },
  lockpick: {
    name: "lockpick",
    close: false,
    label: "Lockpick",
    stack: false,
    usable: true,
    count: 0,
    description:
      "Simple lockpick that breaks easily and can pick basic door locks.",
    rarity: "lendario",
  },
  armour: {
    name: "armour",
    close: false,
    label: "Bulletproof Vest",
    stack: false,
    usable: true,
    count: 0,
    description: "Reduces damage from bullets. Level II protection.",
    rarity: "mitico",
    grid: { width: 2, height: 2 },
  },

  // ---------- misc / supporting items ----------
  burger: {
    name: "burger",
    close: false,
    label: "Burger",
    stack: false,
    usable: false,
    count: 0,
    rarity: "comum",
  },
  card_id: {
    name: "card_id",
    close: false,
    label: "Identification",
    stack: false,
    usable: false,
    count: 0,
    rarity: "comum",
  },
  // ---------- Workbench items ----------
  iron: {
    name: "Iron",
    close: false,
    label: "Barra de ferro",
    stack: true,
    usable: false,
    count: 0,
    rarity: "comum",
  },
  steel: {
    name: "steel",
    close: false,
    label: "Barra de aço",
    stack: true,
    usable: false,
    count: 0,
    rarity: "comum",
  },
  wood: {
    name: "Wood",
    close: false,
    label: "Tabua de madeira",
    stack: true,
    usable: false,
    count: 0,
    rarity: "comum",
  },

  // ---------- 6 weapons, each with a different component loadout ----------
  weapon_pistol: {
    name: "weapon_pistol",
    close: true,
    label: "Pistol",
    stack: false,
    usable: false,
    count: 0,
    description: "A reliable compact sidearm.",
    rarity: "raro",
    ammoName: "ammo_pistol",
  },
  weapon_smg: {
    name: "weapon_smg",
    close: true,
    label: "SMG",
    stack: false,
    usable: false,
    count: 0,
    description: "Compact submachine gun, decent rate of fire.",
    rarity: "epico",
    ammoName: "ammo_smg",
  },
  weapon_assaultrifle: {
    name: "weapon_assaultrifle",
    close: true,
    label: "Assault Rifle",
    stack: false,
    usable: false,
    count: 0,
    description: "Fully modded battle rifle.",
    rarity: "lendario",
    ammoName: "ammo_rifle",
  },
  weapon_sniperrifle: {
    name: "weapon_sniperrifle",
    close: true,
    label: "Sniper Rifle",
    stack: false,
    usable: false,
    count: 0,
    description: "Long-range precision rifle, well worn.",
    rarity: "mitico",
    ammoName: "ammo_sniper",
  },
  weapon_pumpshotgun: {
    name: "weapon_pumpshotgun",
    close: true,
    label: "Pump Shotgun",
    stack: false,
    usable: false,
    count: 0,
    description: "Bare-bones pump-action shotgun, no attachments fitted.",
    rarity: "comum",
    ammoName: "ammo_shotgun",
  },
  weapon_knife: {
    name: "weapon_knife",
    close: true,
    label: "Combat Knife",
    stack: false,
    usable: false,
    count: 0,
    description: "A simple fixed-blade knife. No ammo, no attachments.",
    rarity: "incomum",
  },

  // ---------- weapon components (one per attachment type) ----------
  at_flashlight: {
    name: "at_flashlight",
    close: false,
    label: "Tactical Flashlight",
    stack: true,
    usable: true,
    count: 0,
    type: "flashlight",
  },
  at_muzzle: {
    name: "at_muzzle",
    close: false,
    label: "Suppressor",
    stack: true,
    usable: true,
    count: 0,
    type: "muzzle",
  },
  at_barrel: {
    name: "at_barrel",
    close: false,
    label: "Heavy Barrel",
    stack: true,
    usable: true,
    count: 0,
    type: "barrel",
  },
  at_grip: {
    name: "at_grip",
    close: false,
    label: "Grip",
    stack: true,
    usable: true,
    count: 0,
    type: "grip",
  },
  at_magazine: {
    name: "at_magazine",
    close: false,
    label: "Extended Magazine",
    stack: true,
    usable: true,
    count: 0,
    type: "magazine",
  },
  at_sight: {
    name: "at_sight",
    close: false,
    label: "Holographic Sight",
    stack: true,
    usable: true,
    count: 0,
    type: "sight",
  },
  at_skin: {
    name: "at_skin",
    close: false,
    label: "Urban Skin",
    stack: true,
    usable: true,
    count: 0,
    type: "skin",
  },

  // ---------- ammo (used for the "Tipo de Munição" tooltip/modal row) ----------
  ammo_pistol: {
    name: "ammo_pistol",
    close: false,
    label: ".45 ACP",
    stack: true,
    usable: false,
    count: 0,
  },
  ammo_smg: {
    name: "ammo_smg",
    close: false,
    label: "9mm",
    stack: true,
    usable: false,
    count: 0,
  },
  ammo_rifle: {
    name: "ammo_rifle",
    close: false,
    label: "5.56mm",
    stack: true,
    usable: false,
    count: 0,
  },
  ammo_sniper: {
    name: "ammo_sniper",
    close: false,
    label: ".50 Cal",
    stack: true,
    usable: false,
    count: 0,
  },
  ammo_shotgun: {
    name: "ammo_shotgun",
    close: false,
    label: "12 Gauge",
    stack: true,
    usable: false,
    count: 0,
  },

  // ---------- container ----------
  paperbag: {
    name: "paperbag",
    close: false,
    label: "Paper Bag",
    stack: false,
    usable: true,
    count: 0,
    description: "A simple paper bag for carrying items.",
    rarity: "incomum",
  },
};
